package com.ctm.dal.mapper;

import com.ctm.dal.entity.FlowTemplateDO;
import com.ctm.dal.entity.FlowTemplateDOExample;
import org.apache.ibatis.annotations.Mapper;
import org.apache.ibatis.annotations.Param;

import java.util.List;

@Mapper
public interface FlowTemplateMapper {
    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table
     * flow_template
     *
     * @mbg.generated Sun Aug 28 19:30:45 CST 2022
     */
    long countByExample(FlowTemplateDOExample example);

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table
     * flow_template
     *
     * @mbg.generated Sun Aug 28 19:30:45 CST 2022
     */
    int deleteByExample(FlowTemplateDOExample example);

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table
     * flow_template
     *
     * @mbg.generated Sun Aug 28 19:30:45 CST 2022
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table
     * flow_template
     *
     * @mbg.generated Sun Aug 28 19:30:45 CST 2022
     */
    int insert(FlowTemplateDO record);

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table
     * flow_template
     *
     * @mbg.generated Sun Aug 28 19:30:45 CST 2022
     */
    int insertSelective(FlowTemplateDO record);

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table
     * flow_template
     *
     * @mbg.generated Sun Aug 28 19:30:45 CST 2022
     */
    List<FlowTemplateDO> selectByExample(FlowTemplateDOExample example);

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table
     * flow_template
     *
     * @mbg.generated Sun Aug 28 19:30:45 CST 2022
     */
    FlowTemplateDO selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table
     * flow_template
     *
     * @mbg.generated Sun Aug 28 19:30:45 CST 2022
     */
    int updateByExampleSelective(
            @Param("record") FlowTemplateDO record,
            @Param("example") FlowTemplateDOExample example);

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table
     * flow_template
     *
     * @mbg.generated Sun Aug 28 19:30:45 CST 2022
     */
    int updateByExample(
            @Param("record") FlowTemplateDO record,
            @Param("example") FlowTemplateDOExample example);

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table
     * flow_template
     *
     * @mbg.generated Sun Aug 28 19:30:45 CST 2022
     */
    int updateByPrimaryKeySelective(FlowTemplateDO record);

    /**
     * This method was generated by MyBatis Generator. This method corresponds to the database table
     * flow_template
     *
     * @mbg.generated Sun Aug 28 19:30:45 CST 2022
     */
    int updateByPrimaryKey(FlowTemplateDO record);
}
